import "./globals.css";
import { Header } from "@/components/header/Header";

// this file was generated by next js
// the people who made next js are very smart, and didn't include a test
// I'm gonna assume they knew what they were doing and not test this

export const metadata = {
  title: "matchmake.ink",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
